-- ============================================================
-- SDMU - Sustav za distribuciju medicinskih uređaja
-- Complete PostgreSQL schema
-- ============================================================

-- Drop tables in dependency order
DROP TABLE IF EXISTS Zapisnik CASCADE;
DROP TABLE IF EXISTS Racun CASCADE;
DROP TABLE IF EXISTS Stavka_narudzbe CASCADE;
DROP TABLE IF EXISTS Narudzba_za_kupnju CASCADE;
DROP TABLE IF EXISTS Stavka_ugovora CASCADE;
DROP TABLE IF EXISTS Ugovor_o_najmu CASCADE;
DROP TABLE IF EXISTS Stavka_zahtjeva_najma CASCADE;
DROP TABLE IF EXISTS Zahtjev_za_najam CASCADE;
DROP TABLE IF EXISTS Servis CASCADE;
DROP TABLE IF EXISTS Potrosni_materijal CASCADE;
DROP TABLE IF EXISTS Uredaj CASCADE;
DROP TABLE IF EXISTS Artikl CASCADE;
DROP TABLE IF EXISTS Djelatnik CASCADE;
DROP TABLE IF EXISTS Korisnik CASCADE;


-- ============================================================
-- KORISNIK / CLIENT
-- Medical institution / hospital user
-- ============================================================

CREATE TABLE Korisnik (
    ID_Korisnika INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Naziv_Ustanove VARCHAR(255) NOT NULL,
    OIB CHAR(11) NOT NULL UNIQUE,
    Ulica VARCHAR(255),
    Grad VARCHAR(255),
    Postanski_Broj VARCHAR(20),

    Email VARCHAR(255) NOT NULL UNIQUE,
    Lozinka_Hash VARCHAR(255) NOT NULL,
    Aktivan BOOLEAN NOT NULL DEFAULT TRUE,

    CONSTRAINT chk_korisnik_oib
    CHECK (OIB ~ '^[0-9]{11}$')
);


-- ============================================================
-- DJELATNIK / WORKER
-- Employee with role-based access
-- ============================================================

CREATE TABLE Djelatnik (
    ID_Djelatnika INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Ime_Prezime VARCHAR(255) NOT NULL,
    Uloga VARCHAR(80) NOT NULL,

    Email VARCHAR(255) NOT NULL UNIQUE,
    Lozinka_Hash VARCHAR(255) NOT NULL,
    Aktivan BOOLEAN NOT NULL DEFAULT TRUE,

    CONSTRAINT chk_djelatnik_uloga
    CHECK (Uloga IN (
        'Djelatnik za narudžbe',
        'Djelatnik skladišta',
        'Servisni djelatnik',
        'Administrator'
    ))
);


-- ============================================================
-- ARTIKL
-- Parent table for both rentable devices and consumable goods
-- ============================================================

CREATE TABLE Artikl (
    ID_Artikla INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Naziv_Artikla VARCHAR(255) NOT NULL,
    Proizvodac VARCHAR(255),
    Aktivan BOOLEAN NOT NULL DEFAULT TRUE
);


-- ============================================================
-- UREDAJ
-- Rentable medical equipment
-- ============================================================

CREATE TABLE Uredaj (
    ID_Artikla INT PRIMARY KEY,
    Serijski_Broj VARCHAR(100) NOT NULL UNIQUE,
    Status_Raspolozivosti VARCHAR(50) NOT NULL DEFAULT 'Dostupan',
    Zadana_Cijena_Po_Danu DECIMAL(10,2),

    CONSTRAINT chk_status_uredaja
    CHECK (Status_Raspolozivosti IN (
        'Dostupan',
        'Iznajmljen',
        'Na servisu',
        'Nedostupan'
    )),

    CONSTRAINT chk_uredaj_zadana_cijena
    CHECK (
        Zadana_Cijena_Po_Danu IS NULL
        OR Zadana_Cijena_Po_Danu > 0
    ),

    FOREIGN KEY (ID_Artikla)
    REFERENCES Artikl(ID_Artikla)
    ON DELETE CASCADE
);


-- ============================================================
-- POTROSNI MATERIJAL
-- Consumable goods for purchase/sale
-- ============================================================

CREATE TABLE Potrosni_materijal (
    ID_Artikla INT PRIMARY KEY,
    LOT_Broj VARCHAR(100) NOT NULL,
    Trenutna_Zaliha INT NOT NULL DEFAULT 0,
    Zadana_Jedinicna_Cijena DECIMAL(10,2),

    CONSTRAINT chk_trenutna_zaliha
    CHECK (Trenutna_Zaliha >= 0),

    CONSTRAINT chk_potrosni_zadana_cijena
    CHECK (
        Zadana_Jedinicna_Cijena IS NULL
        OR Zadana_Jedinicna_Cijena > 0
    ),

    FOREIGN KEY (ID_Artikla)
    REFERENCES Artikl(ID_Artikla)
    ON DELETE CASCADE
);


-- ============================================================
-- ZAHTJEV ZA NAJAM
-- Rental request header/master
-- Created by client
-- ============================================================

CREATE TABLE Zahtjev_za_najam (
    ID_Zahtjeva INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Datum_Podnosenja DATE NOT NULL DEFAULT CURRENT_DATE,
    Zeljeni_Datum_Pocetka DATE NOT NULL,
    Zeljeni_Datum_Povrata DATE NOT NULL,
    Status VARCHAR(50) NOT NULL DEFAULT 'Zaprimljen',

    ID_Korisnika INT NOT NULL,
    ID_Djelatnika INT,

    CONSTRAINT chk_zahtjev_datum
    CHECK (Zeljeni_Datum_Povrata > Zeljeni_Datum_Pocetka),

    CONSTRAINT chk_status_zahtjeva
    CHECK (Status IN (
        'Zaprimljen',
        'Odobren',
        'Odbijen',
        'Poništen'
    )),

    FOREIGN KEY (ID_Korisnika)
    REFERENCES Korisnik(ID_Korisnika),

    FOREIGN KEY (ID_Djelatnika)
    REFERENCES Djelatnik(ID_Djelatnika)
);


-- ============================================================
-- STAVKA ZAHTJEVA NAJMA
-- Rental request details/items
-- Client selects devices only, no price here
-- ============================================================

CREATE TABLE Stavka_zahtjeva_najma (
    ID_Zahtjeva INT NOT NULL,
    ID_Artikla INT NOT NULL,

    PRIMARY KEY (ID_Zahtjeva, ID_Artikla),

    FOREIGN KEY (ID_Zahtjeva)
    REFERENCES Zahtjev_za_najam(ID_Zahtjeva)
    ON DELETE CASCADE,

    FOREIGN KEY (ID_Artikla)
    REFERENCES Uredaj(ID_Artikla)
);


-- ============================================================
-- UGOVOR O NAJMU
-- Rental contract header/master
-- Created by worker after approving rental request
-- ============================================================

CREATE TABLE Ugovor_o_najmu (
    ID_Ugovora INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Datum_Sklapanja DATE NOT NULL DEFAULT CURRENT_DATE,
    Ocekivani_Povrat DATE NOT NULL,
    Status VARCHAR(50) NOT NULL DEFAULT 'Na čekanju potvrde korisnika',

    ID_Korisnika INT NOT NULL,
    ID_Djelatnika INT NOT NULL,
    ID_Zahtjeva INT NOT NULL UNIQUE,

    CONSTRAINT chk_status_ugovora
    CHECK (Status IN (
        'Na čekanju potvrde korisnika',
        'Potvrđen',
        'Poništen'
    )),

    FOREIGN KEY (ID_Korisnika)
    REFERENCES Korisnik(ID_Korisnika),

    FOREIGN KEY (ID_Djelatnika)
    REFERENCES Djelatnik(ID_Djelatnika),

    FOREIGN KEY (ID_Zahtjeva)
    REFERENCES Zahtjev_za_najam(ID_Zahtjeva)
);


-- ============================================================
-- STAVKA UGOVORA
-- Contract details/items
-- Worker writes final agreed rental price here
-- ============================================================

CREATE TABLE Stavka_ugovora (
    ID_Ugovora INT NOT NULL,
    ID_Artikla INT NOT NULL,
    Ugovorena_Cijena_Po_Danu DECIMAL(10,2) NOT NULL,

    PRIMARY KEY (ID_Ugovora, ID_Artikla),

    CONSTRAINT chk_cijena_po_danu
    CHECK (Ugovorena_Cijena_Po_Danu > 0),

    FOREIGN KEY (ID_Ugovora)
    REFERENCES Ugovor_o_najmu(ID_Ugovora)
    ON DELETE CASCADE,

    FOREIGN KEY (ID_Artikla)
    REFERENCES Uredaj(ID_Artikla)
);


-- ============================================================
-- NARUDZBA ZA KUPNJU
-- Purchase order header/master
-- Used for buying consumable goods
-- ============================================================

CREATE TABLE Narudzba_za_kupnju (
    ID_Narudzbe INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Datum_Kreiranja DATE NOT NULL DEFAULT CURRENT_DATE,
    Status_Isporuke VARCHAR(50) NOT NULL DEFAULT 'U obradi',

    ID_Korisnika INT NOT NULL,
    ID_Djelatnika INT,

    CONSTRAINT chk_status_isporuke
    CHECK (Status_Isporuke IN (
        'U obradi',
        'Poslano',
        'Isporučeno',
        'Otkazano'
    )),

    FOREIGN KEY (ID_Korisnika)
    REFERENCES Korisnik(ID_Korisnika),

    FOREIGN KEY (ID_Djelatnika)
    REFERENCES Djelatnik(ID_Djelatnika)
);


-- ============================================================
-- STAVKA NARUDZBE
-- Purchase order details/items
-- Used for consumable goods
-- ============================================================

CREATE TABLE Stavka_narudzbe (
    ID_Narudzbe INT NOT NULL,
    ID_Artikla INT NOT NULL,
    Kolicina INT NOT NULL,
    Jedinicna_Cijena DECIMAL(10,2) NOT NULL,

    PRIMARY KEY (ID_Narudzbe, ID_Artikla),

    CONSTRAINT chk_kolicina_narudzbe
    CHECK (Kolicina > 0),

    CONSTRAINT chk_jedinicna_cijena
    CHECK (Jedinicna_Cijena > 0),

    FOREIGN KEY (ID_Narudzbe)
    REFERENCES Narudzba_za_kupnju(ID_Narudzbe)
    ON DELETE CASCADE,

    FOREIGN KEY (ID_Artikla)
    REFERENCES Potrosni_materijal(ID_Artikla)
);


-- ============================================================
-- SERVIS
-- Service/maintenance history for devices
-- ============================================================

CREATE TABLE Servis (
    ID_Servisa INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Datum_Izdavanja DATE NOT NULL DEFAULT CURRENT_DATE,
    Opis_Radova TEXT NOT NULL,
    ID_Artikla INT NOT NULL,

    FOREIGN KEY (ID_Artikla)
    REFERENCES Uredaj(ID_Artikla)
);


-- ============================================================
-- RACUN
-- Invoice
-- Can belong either to rental contract or purchase order
-- ============================================================

CREATE TABLE Racun (
    ID_Racuna INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Ukupan_Iznos DECIMAL(10,2) NOT NULL,
    Datum_Izdavanja DATE NOT NULL DEFAULT CURRENT_DATE,

    ID_Ugovora INT,
    ID_Narudzbe INT,

    CONSTRAINT chk_ukupan_iznos
    CHECK (Ukupan_Iznos >= 0),

    CONSTRAINT chk_racun_izvor
    CHECK (
        (ID_Ugovora IS NOT NULL AND ID_Narudzbe IS NULL)
        OR
        (ID_Ugovora IS NULL AND ID_Narudzbe IS NOT NULL)
    ),

    FOREIGN KEY (ID_Ugovora)
    REFERENCES Ugovor_o_najmu(ID_Ugovora),

    FOREIGN KEY (ID_Narudzbe)
    REFERENCES Narudzba_za_kupnju(ID_Narudzbe)
);


-- ============================================================
-- ZAPISNIK
-- Device handover/return log
-- ============================================================

CREATE TABLE Zapisnik (
    ID_Ugovora INT NOT NULL,
    ID_Artikla INT NOT NULL,
    ID_Djelatnika INT NOT NULL,
    Tip_Akcije VARCHAR(50) NOT NULL,
    Datum_i_Vrijeme TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    PRIMARY KEY (
        ID_Ugovora,
        ID_Artikla,
        ID_Djelatnika,
        Datum_i_Vrijeme
    ),

    CONSTRAINT chk_tip_akcije
    CHECK (Tip_Akcije IN (
        'Izdavanje',
        'Povrat',
        'Napomena'
    )),

    FOREIGN KEY (ID_Ugovora)
    REFERENCES Ugovor_o_najmu(ID_Ugovora),

    FOREIGN KEY (ID_Artikla)
    REFERENCES Uredaj(ID_Artikla),

    FOREIGN KEY (ID_Djelatnika)
    REFERENCES Djelatnik(ID_Djelatnika)
);


-- ============================================================
-- INDEXES
-- ============================================================

CREATE INDEX idx_korisnik_email
ON Korisnik(Email);

CREATE INDEX idx_djelatnik_email
ON Djelatnik(Email);

CREATE INDEX idx_artikl_naziv
ON Artikl(Naziv_Artikla);

CREATE INDEX idx_uredaj_status
ON Uredaj(Status_Raspolozivosti);

CREATE INDEX idx_uredaj_serijski_broj
ON Uredaj(Serijski_Broj);

CREATE INDEX idx_potrosni_lot
ON Potrosni_materijal(LOT_Broj);

CREATE INDEX idx_zahtjev_korisnik
ON Zahtjev_za_najam(ID_Korisnika);

CREATE INDEX idx_zahtjev_status
ON Zahtjev_za_najam(Status);

CREATE INDEX idx_ugovor_korisnik
ON Ugovor_o_najmu(ID_Korisnika);

CREATE INDEX idx_ugovor_status
ON Ugovor_o_najmu(Status);

CREATE INDEX idx_narudzba_korisnik
ON Narudzba_za_kupnju(ID_Korisnika);

CREATE INDEX idx_servis_uredaj
ON Servis(ID_Artikla);


-- ============================================================
-- OPTIONAL SAMPLE DATA WITHOUT PASSWORD HASHES
-- Use your seedUsers.js for real bcrypt password hashes.
-- ============================================================

-- This script intentionally does not insert users because your Node seed script
-- should insert bcrypt hashes for login.